// <auto-generated />
using System;
using App.Infra.Db.SqlServer.Ef.DbContextAgg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infra.Db.SqlServer.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231154943_col ImagePath is not nullable ")]
    partial class colImagePathisnotnullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StaffCode = "ADM-1001",
                            TotalRevenue = 0m
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "081004b3-e25c-4414-9694-44e5c2fd863f",
                            Email = "admin@site.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            ImagePath = "admin.jpg",
                            IsDeleted = false,
                            LastName = "System",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SITE.COM",
                            NormalizedUserName = "ADMIN@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "B6FE5F0E-18B5-4062-AEF8-11555793E7CB",
                            TwoFactorEnabled = false,
                            UserName = "admin@site.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df5dbb19-753c-4cc7-a623-13c8508d00f8",
                            Email = "customer@site.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            ImagePath = "customer1.jpg",
                            IsDeleted = false,
                            LastName = "Moshtari",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@SITE.COM",
                            NormalizedUserName = "CUSTOMER@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "D4D09FBB-ED60-4E17-B03E-B9B4B6C70E5D",
                            TwoFactorEnabled = false,
                            UserName = "customer@site.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58afcc4e-2a82-4ad6-8e12-665778173973",
                            Email = "expert@site.com",
                            EmailConfirmed = true,
                            FirstName = "Reza",
                            ImagePath = "expert1.jpg",
                            IsDeleted = false,
                            LastName = "Karshenas",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT@SITE.COM",
                            NormalizedUserName = "EXPERT@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9489458F-27BA-400D-A45F-AFCE3D9A8D26",
                            TwoFactorEnabled = false,
                            UserName = "expert@site.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C2-04b3-e25c-4414",
                            Email = "customer2@site.com",
                            EmailConfirmed = true,
                            FirstName = "Zahra",
                            ImagePath = "customer2.jpg",
                            IsDeleted = false,
                            LastName = "Ahmadi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@SITE.COM",
                            NormalizedUserName = "CUSTOMER2@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S2-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "customer2@site.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C3-04b3-e25c-4414",
                            Email = "customer3@site.com",
                            EmailConfirmed = true,
                            FirstName = "Mohammad",
                            ImagePath = "customer3.jpg",
                            IsDeleted = false,
                            LastName = "Hosseini",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER3@SITE.COM",
                            NormalizedUserName = "CUSTOMER3@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S3-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "customer3@site.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C4-04b3-e25c-4414",
                            Email = "customer4@site.com",
                            EmailConfirmed = true,
                            FirstName = "Maryam",
                            ImagePath = "customer4.jpg",
                            IsDeleted = false,
                            LastName = "Moradi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER4@SITE.COM",
                            NormalizedUserName = "CUSTOMER4@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S4-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "customer4@site.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C5-04b3-e25c-4414",
                            Email = "customer5@site.com",
                            EmailConfirmed = true,
                            FirstName = "Saeed",
                            ImagePath = "customer5.jpg",
                            IsDeleted = false,
                            LastName = "Karimi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER5@SITE.COM",
                            NormalizedUserName = "CUSTOMER5@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S5-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "customer5@site.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C6-04b3-e25c-4414",
                            Email = "customer6@site.com",
                            EmailConfirmed = true,
                            FirstName = "Niloufar",
                            ImagePath = "customer6.jpg",
                            IsDeleted = false,
                            LastName = "Sadeghi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER6@SITE.COM",
                            NormalizedUserName = "CUSTOMER6@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S6-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "customer6@site.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CE2-04b3-e25c-4414",
                            Email = "expert2@site.com",
                            EmailConfirmed = true,
                            FirstName = "Hassan",
                            ImagePath = "expert2.jpg",
                            IsDeleted = false,
                            LastName = "Alavi",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT2@SITE.COM",
                            NormalizedUserName = "EXPERT2@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E2-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "expert2@site.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CE3-04b3-e25c-4414",
                            Email = "expert3@site.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            ImagePath = "expert3.jpg",
                            IsDeleted = false,
                            LastName = "Mousavi",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT3@SITE.COM",
                            NormalizedUserName = "EXPERT3@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E3-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "expert3@site.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CE4-04b3-e25c-4414",
                            Email = "expert4@site.com",
                            EmailConfirmed = true,
                            FirstName = "Omid",
                            ImagePath = "expert4.jpg",
                            IsDeleted = false,
                            LastName = "Rahmani",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT4@SITE.COM",
                            NormalizedUserName = "EXPERT4@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E4-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "expert4@site.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CE5-04b3-e25c-4414",
                            Email = "expert5@site.com",
                            EmailConfirmed = true,
                            FirstName = "Elham",
                            ImagePath = "expert5.jpg",
                            IsDeleted = false,
                            LastName = "Jafari",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT5@SITE.COM",
                            NormalizedUserName = "EXPERT5@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E5-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "expert5@site.com"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CE6-04b3-e25c-4414",
                            Email = "expert6@site.com",
                            EmailConfirmed = true,
                            FirstName = "Meysam",
                            ImagePath = "expert6.jpg",
                            IsDeleted = false,
                            LastName = "Ghasemi",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXPERT6@SITE.COM",
                            NormalizedUserName = "EXPERT6@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELfo31+h+KKqnm1LH5xAKmHXILVYYm2LFfRa9MBOYhQ7tUa464HktXtipr7xzCC8rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E6-68B5-4062-AEF8",
                            TwoFactorEnabled = false,
                            UserName = "expert6@site.com"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "cleaning-category.jpg",
                            IsDeleted = false,
                            Title = "نظافت و پذیرایی"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "repairs-category.jpg",
                            IsDeleted = false,
                            Title = "تعمیرات و تأسیسات"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "appliances-category.jpg",
                            IsDeleted = false,
                            Title = "تعمیرات لوازم خانگی"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "car-services-category.jpg",
                            IsDeleted = false,
                            Title = "خدمات خودرو"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "beauty-category.jpg",
                            IsDeleted = false,
                            Title = "آرایش و زیبایی"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "moving-category.jpg",
                            IsDeleted = false,
                            Title = "اسباب‌کشی و حمل و نقل"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "gardening-category.jpg",
                            IsDeleted = false,
                            Title = "باغبانی و فضای سبز"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "کرج"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "شیراز"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "اصفهان"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("WalletBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "تهران، خیابان آزادی، پلاک ۱",
                            AppUserId = 2,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 100000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "تهران، سعادت آباد، خیابان سرو",
                            AppUserId = 4,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 50000m
                        },
                        new
                        {
                            Id = 3,
                            Address = "تبریز، ولیعصر، خیابان استانداری",
                            AppUserId = 5,
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 250000m
                        },
                        new
                        {
                            Id = 4,
                            Address = "مشهد، بلوار سجاد، کوچه بهار",
                            AppUserId = 6,
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 0m
                        },
                        new
                        {
                            Id = 5,
                            Address = "تهران، فلکه دوم صادقیه",
                            AppUserId = 7,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 120000m
                        },
                        new
                        {
                            Id = 6,
                            Address = "شیراز، خیابان عفیف آباد، مجتمع ستاره",
                            AppUserId = 8,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 75000m
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<double?>("AverageScore")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("WalletBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.ToTable("Experts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 3,
                            AverageScore = 5.0,
                            Bio = "متخصص در امور فنی با ۱۰ سال سابقه کار",
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 200000m
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 9,
                            AverageScore = 4.0,
                            Bio = "کارشناس ارشد تاسیسات و سیستم‌های برودتی",
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 500000m
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 10,
                            Bio = "متخصص طراحی داخلی و دکوراسیون با مدرک بین‌المللی",
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 1200000m
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 11,
                            Bio = "تکنسین برق قدرت و هوشمندسازی منازل",
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 0m
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 12,
                            AverageScore = 5.0,
                            Bio = "متخصص باغبانی و فضای سبز",
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 350000m
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 13,
                            Bio = "کارشناس تعمیرات لوازم خانگی دیجیتال",
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            WalletBalance = 800000m
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.ExpertHomeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("ExpertHomeServices");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.HomeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("HomeServices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 500000m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "نظافت کامل فضاهای داخلی ساختمان",
                            ImagePath = "cleaning-service.jpg",
                            IsDeleted = false,
                            Name = "نظافت منزل"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 300000m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "سرویس دوره‌ای و تعمیر موتور کولر",
                            ImagePath = "cooler-repair.jpg",
                            IsDeleted = false,
                            Name = "تعمیر کولر آبی"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 800000m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "عیب‌یابی و شارژ گاز انواع یخچال‌های ایرانی و خارجی",
                            ImagePath = "fridge-repair.jpg",
                            IsDeleted = false,
                            Name = "تعمیر یخچال و فریزر"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 250000m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "شستشوی کامل بدنه و داخل خودرو با نانو بدون آب",
                            ImagePath = "carwash-service.jpg",
                            IsDeleted = false,
                            Name = "کارواش در محل"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 400000m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "خدمات آرایشی مردانه و زنانه در منزل شما",
                            ImagePath = "barber-service.jpg",
                            IsDeleted = false,
                            Name = "اصلاح سر و صورت"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 1500000m,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "جمع‌آوری وسایل و حمل اثاثیه با کادر مجرب",
                            ImagePath = "moving-service.jpg",
                            IsDeleted = false,
                            Name = "بسته‌بندی و اسباب‌کشی"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 600000m,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "رسیدگی به باغچه و طراحی فضای سبز",
                            ImagePath = "gardening-service.jpg",
                            IsDeleted = false,
                            Name = "هرس درختان و گل‌کاری"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("time");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Description = "نظافت آپارتمان ۸۰ متری، دو خوابه",
                            ExecutionDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 10, 0, 0, 0),
                            HomeServiceId = 1,
                            IsDeleted = false,
                            Status = 5
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Description = "یخچال ساید بای ساید صدای ناهنجار می‌دهد",
                            ExecutionDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 14, 30, 0, 0),
                            HomeServiceId = 3,
                            IsDeleted = false,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Description = "سرویس کامل کولر آبی برای فصل جدید",
                            ExecutionDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 9, 0, 0, 0),
                            HomeServiceId = 2,
                            IsDeleted = false,
                            Status = 5
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            Description = "شستشوی کامل پژو ۲۰۶ در پارکینگ منزل",
                            ExecutionDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 16, 0, 0, 0),
                            HomeServiceId = 4,
                            IsDeleted = false,
                            Status = 6
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            Description = "هرس درختان حیاط و کاشت گل‌های فصلی",
                            ExecutionDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 8, 0, 0, 0),
                            HomeServiceId = 7,
                            IsDeleted = false,
                            Status = 5
                        },
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            Description = "جابجایی اثاثیه به ساختمان مجاور، طبقه سوم با آسانسور",
                            ExecutionDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutionTime = new TimeSpan(0, 11, 0, 0, 0),
                            HomeServiceId = 6,
                            IsDeleted = false,
                            Status = 4
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.OrderImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "apartment-cleaning-1.jpg",
                            IsDeleted = false,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "apartment-cleaning-2.jpg",
                            IsDeleted = false,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "fridge-issue-photo.jpg",
                            IsDeleted = false,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 20, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "cooler-on-roof.jpg",
                            IsDeleted = false,
                            OrderId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "dirty-car-front.jpg",
                            IsDeleted = false,
                            OrderId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "garden-yard-view.jpg",
                            IsDeleted = false,
                            OrderId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 2, 22, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "moving-boxes.jpg",
                            IsDeleted = false,
                            OrderId = 6
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId");

                    b.ToTable("Proposals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "با تجهیزات کامل نظافتی در زمان تعیین شده حضور خواهم یافت.",
                            ExpertId = 1,
                            IsDeleted = false,
                            OrderId = 1,
                            Price = 550000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تضمین نظافت کامل با قیمت مناسب‌تر.",
                            ExpertId = 4,
                            IsDeleted = false,
                            OrderId = 1,
                            Price = 500000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "قطعات اصلی و ضمانت ۶ ماهه تعمیرات.",
                            ExpertId = 6,
                            IsDeleted = false,
                            OrderId = 2,
                            Price = 850000m,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "سرویس کامل کولر شامل شستشو و روغن‌کاری.",
                            ExpertId = 2,
                            IsDeleted = false,
                            OrderId = 3,
                            Price = 350000m,
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "طراحی باغچه و هرس تخصصی درختان میوه.",
                            ExpertId = 5,
                            IsDeleted = false,
                            OrderId = 5,
                            Price = 650000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "دارای ماشین مخصوص و کارگران ورزیده.",
                            ExpertId = 1,
                            IsDeleted = false,
                            OrderId = 6,
                            Price = 1600000m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "سرویس کولر خیلی خوب انجام شد، فقط کمی با تاخیر آمدند.",
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            ExpertId = 2,
                            IsDeleted = false,
                            OrderId = 3,
                            Score = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "باغبانی عالی و حرفه‌ای! حیاط ما کاملاً متحول شد. ممنونم از خانم جعفری.",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            ExpertId = 5,
                            IsDeleted = false,
                            OrderId = 5,
                            Score = 5
                        },
                        new
                        {
                            Id = 3,
                            Comment = "بسیار تمیز و با حوصله کار انجام شد. راضی بودم.",
                            CreatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ExpertId = 1,
                            IsDeleted = false,
                            OrderId = 1,
                            Score = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "78641951-8712-4261-9B5A-431A29D67A41",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "45127812-1234-5678-9B5A-431A29D67A42",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "12345678-8712-4261-9B5A-431A29D67A43",
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Admin", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", "AppUser")
                        .WithOne("AdminProfile")
                        .HasForeignKey("App.Domain.Core.Entities.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Customer", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", "AppUser")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("App.Domain.Core.Entities.Customer", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("App.Domain.Core.Entities.City", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("City");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Expert", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", "AppUser")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("App.Domain.Core.Entities.Expert", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("App.Domain.Core.Entities.City", "City")
                        .WithMany("Experts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("City");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.ExpertHomeService", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("ExpertHomeServices")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.HomeService", "HomeService")
                        .WithMany("ExpertHomeServices")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.HomeService", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Order", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.City", "City")
                        .WithMany("Orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.HomeService", "HomeService")
                        .WithMany("Orders")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.OrderImage", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Order", "Order")
                        .WithMany("Images")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Proposal", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Proposals")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.Order", "Order")
                        .WithMany("Proposals")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Review", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Reviews")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("App.Domain.Core.Entities.Review", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Core.Entities.AppUser", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("CustomerProfile");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.City", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Experts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Expert", b =>
                {
                    b.Navigation("ExpertHomeServices");

                    b.Navigation("Proposals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.HomeService", b =>
                {
                    b.Navigation("ExpertHomeServices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("App.Domain.Core.Entities.Order", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Proposals");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
